apiVersion:apps/v1
kind:Deployment
metadata:
  name:nginx-deployment
  spec:
  replicas:3
  selector:
    matchLabels:
      app:nginx
  template:
    metadata:
      name:nginx-pod
      labels:
        app:nginx
    spec:
      containers:
      -name:nginx-cont
        image:docker.io/nginx:alpine
        image:docker.io/nginx:latest
