apiVersion:v1
kind:Pod
metadata:
  name:new-pod
  labels:
    tier:frontend
    app:webapp
spec:
  containers:
  -name:my-container
  image:docker.io/nginx:alpine
  ports:
  -containerPort:80
  